### ISSUE TITLE
main.py运行后需要修改些什么？

### ISSUE THREAD

**Issue by Chenilove** [huan-yp/Auto-WSGR#1]
我对项目现在的状态有些疑惑，作者是写好了接口让其他人调用吗？
作者平时是怎么测试的？

**Comment by Nickydusk** [comment]
目前是只有接口，有一些已经可以使用的功能需要看看代码了解一下，晚点更新README

**Comment by huan-yp** [comment]
ReadMe 已经更新，并对接口做了调整，请重新下载 Release 中的代码并参考 ReadMe 使用。

**Comment by Chenilove** [comment]
> ReadMe 已经更新，并对接口做了调整，请重新下载 Release 中的代码并参考 ReadMe 使用。

好的，谢谢作者，看到了。
对了，我看作者好像想公开笔记，不过因为没有授予其他人访问权限，所以所有人无法查看笔记。

**Comment by Nickydusk** [comment]
> 我对项目现在的状态有些疑惑，作者是写好了接口让其他人调用吗？ 作者平时是怎么测试的？

目前已完成更多上层API，并提供了一个日常挂机的简单脚本，可以参考着用
