### ISSUE TITLE
错误提示无法找到res.out。

### ISSUE THREAD

**Issue by veadex** [huan-yp/Auto-WSGR#15]
在运行的时候，选完舰队出征之后，在开始战斗的界面会报错FileNotFoundError: file c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages\AutoWSGR\bin\image_recognize\res.outnot found
具体代码如下
`[INFO 00:21:58 root] Hello,I am WSGR auto commanding system
[INFO 00:22:00 root] resolution:(1280, 720)
[INFO 00:22:03 root] Now at: main_page
'c:\users\xu' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
2023-04-24 00:22:11.836 Uncaught app exception
Traceback (most recent call last):
  File "c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\xu jihu\Downloads\Compressed\AutoWSGR-GUI-main\AutoWSGR-GUI-main\pages\2_🎣_日常挂机.py", line 17, in <module>
    operation.run()
  File "c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages\AutoWSGR\scripts\daily_api.py", line 46, in run
    ret = plan.run()
  File "c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages\AutoWSGR\fight\common.py", line 302, in run
    return self.fight()
  File "c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages\AutoWSGR\fight\common.py", line 248, in fight
    ret = self._make_decision()
  File "c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages\AutoWSGR\fight\normal_fight.py", line 251, in _make_decision
    state = self.update_state()
  File "c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages\AutoWSGR\fight\common.py", line 336, in update_state
    self.Info.update_state()
  File "c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages\AutoWSGR\fight\common.py", line 157, in update_state
    self._after_match()
  File "c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages\AutoWSGR\fight\normal_fight.py", line 103, in _after_match
    GetEnemyCondition(self.timer, 'fight')
  File "c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages\AutoWSGR\game\get_game_info.py", line 111, in GetEnemyCondition
    res = read_file(os.path.join(TUNNEL_ROOT, "res.out")).split()
  File "c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages\AutoWSGR\utils\io.py", line 85, in read_file
    raise FileNotFoundError("file " + os.path.abspath(path) + "not found")
FileNotFoundError: file c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages\AutoWSGR\bin\image_recognize\res.outnot found`
![image](https://user-images.githubusercontent.com/65024689/233852009-31510230-e86e-4147-b5a7-b77846e6f461.png)

**Comment by huan-yp** [comment]
请拉取最新版本的后端，这个错误是由于 .gitigonre 配置错误导致的，已经在最新版（github 版本）后端中修复，使用以下命令拉去最新版后端：
`pip install -U git+https://github.com/huan-yp/Auto-WSGR.git@main`

**Comment by veadex** [comment]
我是昨天晚上刚装上的，今天早晨的时候我也尝试着拉取最新的版本，运行的时候还是会有这个报错，错误代码没有变化

**Comment by veadex** [comment]
`C:\Users\xu jihu>pip install -U git+https://github.com/huan-yp/Auto-WSGR.git@main
Collecting git+https://github.com/huan-yp/Auto-WSGR.git@main
  Cloning https://github.com/huan-yp/Auto-WSGR.git (to revision main) to c:\users\xu jihu\appdata\local\temp\pip-req-build-ou3xa2g8
  Running command git clone --filter=blob:none --quiet https://github.com/huan-yp/Auto-WSGR.git 'C:\Users\xu jihu\AppData\Local\Temp\pip-req-build-ou3xa2g8'
  Resolved https://github.com/huan-yp/Auto-WSGR.git to commit d4d8d456e6411dfdef2140f073abf25421b72c51
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: opencv-python==4.5.4.60 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from AutoWSGR==0.0.9) (4.5.4.60)
Requirement already satisfied: opencv-contrib-python==4.5.4.60 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from AutoWSGR==0.0.9) (4.5.4.60)
Requirement already satisfied: opencv-python-headless==4.5.4.60 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from AutoWSGR==0.0.9) (4.5.4.60)
Requirement already satisfied: airtest in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from AutoWSGR==0.0.9) (1.2.10)
Requirement already satisfied: keyboard in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from AutoWSGR==0.0.9) (0.13.5)
Requirement already satisfied: easyocr in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from AutoWSGR==0.0.9) (1.6.2)
Requirement already satisfied: streamlit in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from AutoWSGR==0.0.9) (1.21.0)
Requirement already satisfied: numpy>=1.17.3 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from opencv-contrib-python==4.5.4.60->AutoWSGR==0.0.9) (1.19.5)
Requirement already satisfied: Jinja2>=2.8 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from airtest->AutoWSGR==0.0.9) (3.1.2)
Requirement already satisfied: Pillow>=3.4.0 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from airtest->AutoWSGR==0.0.9) (9.5.0)
Requirement already satisfied: requests>=2.11.1 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from airtest->AutoWSGR==0.0.9) (2.28.2)
Requirement already satisfied: six in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from airtest->AutoWSGR==0.0.9) (1.16.0)
Requirement already satisfied: mss==6.1.0 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from airtest->AutoWSGR==0.0.9) (6.1.0)
Requirement already satisfied: facebook-wda>=1.3.3 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from airtest->AutoWSGR==0.0.9) (1.4.6)
Requirement already satisfied: pywinauto==0.6.3 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from airtest->AutoWSGR==0.0.9) (0.6.3)
Requirement already satisfied: filelock in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from airtest->AutoWSGR==0.0.9) (3.12.0)
Requirement already satisfied: ffmpeg-python in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from airtest->AutoWSGR==0.0.9) (0.2.0)
Requirement already satisfied: pywin32 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from airtest->AutoWSGR==0.0.9) (306)
Requirement already satisfied: comtypes in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from pywinauto==0.6.3->airtest->AutoWSGR==0.0.9) (1.1.14)
Requirement already satisfied: pypiwin32 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from pywinauto==0.6.3->airtest->AutoWSGR==0.0.9) (223)
Requirement already satisfied: torch in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from easyocr->AutoWSGR==0.0.9) (2.0.0)
Requirement already satisfied: torchvision>=0.5 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from easyocr->AutoWSGR==0.0.9) (0.15.1)
Requirement already satisfied: scipy in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from easyocr->AutoWSGR==0.0.9) (1.10.1)
Requirement already satisfied: scikit-image in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from easyocr->AutoWSGR==0.0.9) (0.19.3)
Requirement already satisfied: python-bidi in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from easyocr->AutoWSGR==0.0.9) (0.4.2)
Requirement already satisfied: PyYAML in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from easyocr->AutoWSGR==0.0.9) (6.0)
Requirement already satisfied: Shapely in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from easyocr->AutoWSGR==0.0.9) (2.0.1)
Requirement already satisfied: pyclipper in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from easyocr->AutoWSGR==0.0.9) (1.3.0.post4)
Requirement already satisfied: ninja in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from easyocr->AutoWSGR==0.0.9) (1.11.1)
Requirement already satisfied: altair<5,>=3.2.0 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from streamlit->AutoWSGR==0.0.9) (4.2.2)
Requirement already satisfied: blinker>=1.0.0 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from streamlit->AutoWSGR==0.0.9) (1.6.2)
Requirement already satisfied: cachetools>=4.0 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from streamlit->AutoWSGR==0.0.9) (5.3.0)
Requirement already satisfied: click>=7.0 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from streamlit->AutoWSGR==0.0.9) (8.1.3)
Requirement already satisfied: importlib-metadata>=1.4 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from streamlit->AutoWSGR==0.0.9) (6.6.0)
Requirement already satisfied: packaging>=14.1 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from streamlit->AutoWSGR==0.0.9) (23.1)
Requirement already satisfied: pandas<2,>=0.25 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from streamlit->AutoWSGR==0.0.9) (1.4.4)
Requirement already satisfied: protobuf<4,>=3.12 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from streamlit->AutoWSGR==0.0.9) (3.20.3)
Requirement already satisfied: pyarrow>=4.0 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from streamlit->AutoWSGR==0.0.9) (11.0.0)
Requirement already satisfied: pympler>=0.9 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from streamlit->AutoWSGR==0.0.9) (1.0.1)
Requirement already satisfied: python-dateutil in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from streamlit->AutoWSGR==0.0.9) (2.8.2)
Requirement already satisfied: rich>=10.11.0 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from streamlit->AutoWSGR==0.0.9) (13.3.4)
Requirement already satisfied: toml in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from streamlit->AutoWSGR==0.0.9) (0.10.2)
Requirement already satisfied: typing-extensions>=3.10.0.0 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from streamlit->AutoWSGR==0.0.9) (4.5.0)
Requirement already satisfied: tzlocal>=1.1 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from streamlit->AutoWSGR==0.0.9) (4.3)
Requirement already satisfied: validators>=0.2 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from streamlit->AutoWSGR==0.0.9) (0.20.0)
Requirement already satisfied: gitpython!=3.1.19 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from streamlit->AutoWSGR==0.0.9) (3.1.31)
Requirement already satisfied: pydeck>=0.1.dev5 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from streamlit->AutoWSGR==0.0.9) (0.8.1b0)
Requirement already satisfied: tornado>=6.0.3 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from streamlit->AutoWSGR==0.0.9) (6.3.1)
Requirement already satisfied: watchdog in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from streamlit->AutoWSGR==0.0.9) (3.0.0)
Requirement already satisfied: entrypoints in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from altair<5,>=3.2.0->streamlit->AutoWSGR==0.0.9) (0.4)
Requirement already satisfied: jsonschema>=3.0 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from altair<5,>=3.2.0->streamlit->AutoWSGR==0.0.9) (4.17.3)
Requirement already satisfied: toolz in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from altair<5,>=3.2.0->streamlit->AutoWSGR==0.0.9) (0.12.0)
Requirement already satisfied: colorama in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from click>=7.0->streamlit->AutoWSGR==0.0.9) (0.4.6)
Requirement already satisfied: retry in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from facebook-wda>=1.3.3->airtest->AutoWSGR==0.0.9) (0.9.2)
Requirement already satisfied: cached-property~=1.5.1 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from facebook-wda>=1.3.3->airtest->AutoWSGR==0.0.9) (1.5.2)
Requirement already satisfied: Deprecated~=1.2.6 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from facebook-wda>=1.3.3->airtest->AutoWSGR==0.0.9) (1.2.13)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from gitpython!=3.1.19->streamlit->AutoWSGR==0.0.9) (4.0.10)
Requirement already satisfied: zipp>=0.5 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from importlib-metadata>=1.4->streamlit->AutoWSGR==0.0.9) (3.15.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from Jinja2>=2.8->airtest->AutoWSGR==0.0.9) (2.1.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from pandas<2,>=0.25->streamlit->AutoWSGR==0.0.9) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from requests>=2.11.1->airtest->AutoWSGR==0.0.9) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from requests>=2.11.1->airtest->AutoWSGR==0.0.9) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from requests>=2.11.1->airtest->AutoWSGR==0.0.9) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from requests>=2.11.1->airtest->AutoWSGR==0.0.9) (2022.12.7)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from rich>=10.11.0->streamlit->AutoWSGR==0.0.9) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from rich>=10.11.0->streamlit->AutoWSGR==0.0.9) (2.15.1)
Requirement already satisfied: sympy in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from torch->easyocr->AutoWSGR==0.0.9) (1.11.1)
Requirement already satisfied: networkx in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from torch->easyocr->AutoWSGR==0.0.9) (3.1)
Requirement already satisfied: pytz-deprecation-shim in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from tzlocal>=1.1->streamlit->AutoWSGR==0.0.9) (0.1.0.post0)
Requirement already satisfied: tzdata in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from tzlocal>=1.1->streamlit->AutoWSGR==0.0.9) (2023.3)
Requirement already satisfied: backports.zoneinfo in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from tzlocal>=1.1->streamlit->AutoWSGR==0.0.9) (0.2.1)
Requirement already satisfied: decorator>=3.4.0 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from validators>=0.2->streamlit->AutoWSGR==0.0.9) (5.1.1)
Requirement already satisfied: future in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from ffmpeg-python->airtest->AutoWSGR==0.0.9) (0.18.3)
Requirement already satisfied: imageio>=2.4.1 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from scikit-image->easyocr->AutoWSGR==0.0.9) (2.27.0)
Requirement already satisfied: tifffile>=2019.7.26 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from scikit-image->easyocr->AutoWSGR==0.0.9) (2023.4.12)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from scikit-image->easyocr->AutoWSGR==0.0.9) (1.4.1)
Requirement already satisfied: wrapt<2,>=1.10 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from Deprecated~=1.2.6->facebook-wda>=1.3.3->airtest->AutoWSGR==0.0.9) (1.15.0)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19->streamlit->AutoWSGR==0.0.9) (5.0.0)
Requirement already satisfied: attrs>=17.4.0 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from jsonschema>=3.0->altair<5,>=3.2.0->streamlit->AutoWSGR==0.0.9) (23.1.0)
Requirement already satisfied: importlib-resources>=1.4.0 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from jsonschema>=3.0->altair<5,>=3.2.0->streamlit->AutoWSGR==0.0.9) (5.12.0)
Requirement already satisfied: pkgutil-resolve-name>=1.3.10 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from jsonschema>=3.0->altair<5,>=3.2.0->streamlit->AutoWSGR==0.0.9) (1.3.10)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from jsonschema>=3.0->altair<5,>=3.2.0->streamlit->AutoWSGR==0.0.9) (0.19.3)
Requirement already satisfied: mdurl~=0.1 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=10.11.0->streamlit->AutoWSGR==0.0.9) (0.1.2)
Requirement already satisfied: py<2.0.0,>=1.4.26 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from retry->facebook-wda>=1.3.3->airtest->AutoWSGR==0.0.9) (1.11.0)
Requirement already satisfied: mpmath>=0.19 in c:\users\xu jihu\appdata\local\programs\python\python38\lib\site-packages (from sympy->torch->easyocr->AutoWSGR==0.0.9) (1.3.0)`
这个是我更新时候的代码

**Comment by huan-yp** [comment]
检查一下 Python 安装路径下里的 `Lib\site-packages\AutoWSGR\bin\image_recognize` 里有没有 `TemplateData` 和 `recognize_enemy.exe`，这个错误是由于缺失这两个文件导致的，手动更新应该会添加这两个文件，你也可以从 github 上把这两个文件下载下来复制进去，如果你没有计算机基础不知道怎么做，可以加群问。

**Comment by veadex** [comment]
是有这两个文件的，现在能打战役，就是安排出征的时候会报错，无论是8-1a还是8-2b

**Comment by huan-yp** [comment]
那就有可能是杀毒软件把这个 .exe 的运行拦截了，检查一下杀毒软件的日志，并添加白名单

**Comment by veadex** [comment]
我没有装任何杀毒软件，只有自带的windows defender，这个也被我关了，

**Comment by veadex** [comment]
那我换后端用吧还是，还有一个bug，就是前段生成user_setting.yaml文件的时候，plan0不知道为什么会生成null，然后会提示none.yaml找不到这个文件，这是我之前遇到的一个bug

**Comment by huan-yp** [comment]
回答你的问题之前我尝试在一台全新的机子上配置并运行了 GUI，没有出现任何问题，res.out 文件是深海舰队识别模块的输出，recognize.exe 为 C++ 语言编写的识别模块的可执行文件，没有输出的原因只能是 recognize.exe 文件无法正常运行，建议你检查 recognize.exe 文件是否能够正常执行，如果其它模块运行正常，那么在 recognize 文件夹下会有一个 `args.in` 文件，你可以用命令行在该目录执行 `.\recognize_enemy.exe . ` 命令检查该文件是否可以正常执行，我预期是无法正常执行并得到 res.out 输出，请根据执行的报错情况自行排查或者提问。

**Comment by huan-yp** [comment]
> 那我换后端用吧还是，还有一个bug，就是前段生成user_setting.yaml文件的时候，plan0不知道为什么会生成null，然后会提示none.yaml找不到这个文件，这是我之前遇到的一个bug

生成 user_setting.yaml 的问题是前端的问题，换成后端版本可以解决。

**Comment by veadex** [comment]
> 回答你的问题之前我尝试在一台全新的机子上配置并运行了 GUI，没有出现任何问题，res.out 文件是深海舰队识别模块的输出，recognize.exe 为 C++ 语言编写的识别模块的可执行文件，没有输出的原因只能是 recognize.exe 文件无法正常运行，建议你检查 recognize.exe 文件是否能够正常执行，如果其它模块运行正常，那么在 recognize 文件夹下会有一个 `args.in` 文件，你可以用命令行在该目录执行 `.\recognize_enemy.exe . ` 命令检查该文件是否可以正常执行，我预期是无法正常执行并得到 res.out 输出，请根据执行的报错情况自行排查或者提问。
> 
> 另外，这个问题不是前端的锅。

在bin目录下确实有ARGs.in文件，在我使用命令行启动.exe文件之后，命令行执行没有报错，直接没有任何反馈，`C:\Users\xu jihu\AppData\Local\Programs\Python\Python38\Lib\site-packages\AutoWSGR\bin\image_recognize>.\recognize_enemy.exe

C:\Users\xu jihu\AppData\Local\Programs\Python\Python38\Lib\site-packages\AutoWSGR\bin\image_recognize>.\recognize_enemy.exe`
我再自己排查一下吧，谢谢大佬₍˄·͈༝·͈˄*₎◞ ̑̑

**Comment by huan-yp** [comment]
recognize.exe 的运行参数有两个，第一个是文件路径参数，第二个是工作目录。
工作目录一般就设置为 recognize 文件夹。
为啥不用我给的命令运行呢/wul/wul
在 recognize 文件夹打开终端，执行
`.\recognize.exe .`
运行之后检查工作目录下是否有 res.out 输出

**Comment by veadex** [comment]
看错了，我还以为那个点是我屏幕上的灰尘呢，我是直接用的tab补全的命令，现在我用了你的命令之后确实生成了一个`res.out`文件，我又尝试运行了一下，仍然是提示没有找到res.out文件
ps：用户名是懒得隐藏了，准备之后改掉0v0

**Comment by huan-yp** [comment]
用纯后端版本调试一下吧，这个是真的不知道原因了。
可能的原因太多了/wul/wul。
剩下的可能性就是工作路径这些没有配置正确了，环境问题比代码问题难搞多了/ww/ww
实在解决不了可以加 qq 群进一步交流吧

**Comment by veadex** [comment]
好的，我再去检查一下环境，谢谢0v0

**Comment by veadex** [comment]
我现在对这个报错有个猜想，今天下午我重装了一遍系统，将我的用户名改为了xx，去掉了原来的用户名中间的空格，现在可以正常运行了，在之前的代码运行中出现过`'c:\users\xu' 不是内部或外部命令，也不是可运行的程序 或批处理文件。`的报错，我想是不是因为这个空格的问题，导致路径错误，无法在指定路径生成文件？

**Comment by huan-yp** [comment]
有这个可能，我修一下 bug 吧

**Comment by huan-yp** [comment]
fixed in this commit
https://github.com/huan-yp/Auto-WSGR/commit/e91eea7f412916ad9c354b19c54a3e64d35e7294
