### ISSUE TITLE
setup.py 无法使用

### ISSUE THREAD

**Issue by NNN-545** [huan-yp/Auto-WSGR#2]
从github上下载的包里面的setup.py 无法使用
显示缺少whell库之后窗口会自动退出。

但是我检查了anaconda的环境之后，发现这个库已经装过了。

ps：直接pip install 安装成功

**Comment by huan-yp** [comment]
感谢反馈！  

github 上不是稳定版，由于做决战改动较大导致有些问题没有处理干净，等作者放假回去处理。

**Comment by NNN-545** [comment]
另外，尝试运行挂机策略时，出现了大段报错，日志放在下面了
可以参考一下这个项目，https://github.com/MaaAssistantArknights/MaaAssistantArknights，也采用了类似的技术，目前实现了稳定运行
感谢你的工作（仓鼠一直想有这种项目）

**>>> operation = DailyOperation("C:\\Users\\23576\\Desktop\\Auto-WSGR-main\\examples\\user_settings.yaml")**
这一行需要给绝对路径，不然也会报找不到文件
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\23576\anaconda3\lib\site-packages\AutoWSGR\daily_api.py", line 11, in __init__
    self.timer = start_script(setting_path)
  File "C:\Users\23576\anaconda3\lib\site-packages\AutoWSGR\main.py", line 30, in start_script
    timer.setup(to_main_page)
  File "C:\Users\23576\anaconda3\lib\site-packages\AutoWSGR\controller\run_timer.py", line 55, in setup
    self.connect(S.device_name)
  File "C:\Users\23576\anaconda3\lib\site-packages\AutoWSGR\controller\emulator.py", line 40, in connect
    self.Windows.ConnectAndroid()
  File "C:\Users\23576\anaconda3\lib\site-packages\AutoWSGR\utils\function_wrapper.py", line 20, in imtemplate
    return fun(*arg, **kwargs)
  File "C:\Users\23576\anaconda3\lib\site-packages\AutoWSGR\controller\windows_controller.py", line 80, in ConnectAndroid
    if self.is_android_online(5) == False:
  File "C:\Users\23576\anaconda3\lib\site-packages\AutoWSGR\controller\windows_controller.py", line 101, in is_android_online
    res = check_output("adb devices -l").decode('ascii').split('\n')
  File "C:\Users\23576\anaconda3\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\23576\anaconda3\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\23576\anaconda3\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\23576\anaconda3\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by huan-yp** [comment]
额，这个项目目前还正在进行功能完善以及，对运行环境配置没有做太多考虑，暂时还得麻烦用户自行处理一些问题。
等所有功能齐全后会重点解决环境问题，如果存在无法解决的问题欢迎在 Issue 里提出，也欢迎分享运行时碰见的问题。

**Comment by Nickydusk** [comment]
> 另外，尝试运行挂机策略时，出现了大段报错，日志放在下面了 可以参考一下这个项目，[https://github.com/MaaAssistantArknights/MaaAssistantArknights，也采用了类似的技术，目前实现了稳定运行](https://github.com/MaaAssistantArknights/MaaAssistantArknights%EF%BC%8C%E4%B9%9F%E9%87%87%E7%94%A8%E4%BA%86%E7%B1%BB%E4%BC%BC%E7%9A%84%E6%8A%80%E6%9C%AF%EF%BC%8C%E7%9B%AE%E5%89%8D%E5%AE%9E%E7%8E%B0%E4%BA%86%E7%A8%B3%E5%AE%9A%E8%BF%90%E8%A1%8C) 感谢你的工作（仓鼠一直想有这种项目）
> 
> **>>> operation = DailyOperation("C:\Users\23576\Desktop\Auto-WSGR-main\examples\user_settings.yaml")** 这一行需要给绝对路径，不然也会报找不到文件 Traceback (most recent call last): File "", line 1, in File "C:\Users\23576\anaconda3\lib\site-packages\AutoWSGR\daily_api.py", line 11, in **init** self.timer = start_script(setting_path) File "C:\Users\23576\anaconda3\lib\site-packages\AutoWSGR\main.py", line 30, in start_script timer.setup(to_main_page) File "C:\Users\23576\anaconda3\lib\site-packages\AutoWSGR\controller\run_timer.py", line 55, in setup self.connect(S.device_name) File "C:\Users\23576\anaconda3\lib\site-packages\AutoWSGR\controller\emulator.py", line 40, in connect self.Windows.ConnectAndroid() File "C:\Users\23576\anaconda3\lib\site-packages\AutoWSGR\utils\function_wrapper.py", line 20, in imtemplate return fun(*arg, **kwargs) File "C:\Users\23576\anaconda3\lib\site-packages\AutoWSGR\controller\windows_controller.py", line 80, in ConnectAndroid if self.is_android_online(5) == False: File "C:\Users\23576\anaconda3\lib\site-packages\AutoWSGR\controller\windows_controller.py", line 101, in is_android_online res = check_output("adb devices -l").decode('ascii').split('\n') File "C:\Users\23576\anaconda3\lib\subprocess.py", line 424, in check_output return run(*popenargs, stdout=PIPE, timeout=timeout, check=True, File "C:\Users\23576\anaconda3\lib\subprocess.py", line 505, in run with Popen(*popenargs, **kwargs) as process: File "C:\Users\23576\anaconda3\lib\subprocess.py", line 951, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "C:\Users\23576\anaconda3\lib\subprocess.py", line 1420, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] 系统找不到指定的文件。

- 相对路径是相对于工作目录（命令行左边显示的路径）而言的，你所描述的问题有可能是由于没有在examples/目录下运行脚本，而在根目录下直接运行。之后的版本中我们会改一下这里的写法，让他用相对文件的路径，避免出错。
- 第二条的原因仅通过res = check_output("adb devices -l").decode('ascii').split('\n')，我怀疑可能是因为你的电脑没有安装过gdb，导致运行指令的时候找不到该指令而出错。可以参考https://blog.csdn.net/m0_64776928/article/details/125869652的教程安装一下，确保电脑中adb -V能正确显示后再试试我们的代码。
- 感谢你的反馈，adb依赖问题会在之后的稳定发布版本中整合到一起。

**Comment by huan-yp** [comment]
> 另外，尝试运行挂机策略时，出现了大段报错，日志放在下面了 可以参考一下这个项目，[https://github.com/MaaAssistantArknights/MaaAssistantArknights，也采用了类似的技术，目前实现了稳定运行](https://github.com/MaaAssistantArknights/MaaAssistantArknights%EF%BC%8C%E4%B9%9F%E9%87%87%E7%94%A8%E4%BA%86%E7%B1%BB%E4%BC%BC%E7%9A%84%E6%8A%80%E6%9C%AF%EF%BC%8C%E7%9B%AE%E5%89%8D%E5%AE%9E%E7%8E%B0%E4%BA%86%E7%A8%B3%E5%AE%9A%E8%BF%90%E8%A1%8C) 感谢你的工作（仓鼠一直想有这种项目）
> 
> **>>> operation = DailyOperation("C:\Users\23576\Desktop\Auto-WSGR-main\examples\user_settings.yaml")** 这一行需要给绝对路径，不然也会报找不到文件 Traceback (most recent call last): File "", line 1, in File "C:\Users\23576\anaconda3\lib\site-packages\AutoWSGR\daily_api.py", line 11, in **init** self.timer = start_script(setting_path) File "C:\Users\23576\anaconda3\lib\site-packages\AutoWSGR\main.py", line 30, in start_script timer.setup(to_main_page) File "C:\Users\23576\anaconda3\lib\site-packages\AutoWSGR\controller\run_timer.py", line 55, in setup self.connect(S.device_name) File "C:\Users\23576\anaconda3\lib\site-packages\AutoWSGR\controller\emulator.py", line 40, in connect self.Windows.ConnectAndroid() File "C:\Users\23576\anaconda3\lib\site-packages\AutoWSGR\utils\function_wrapper.py", line 20, in imtemplate return fun(*arg, **kwargs) File "C:\Users\23576\anaconda3\lib\site-packages\AutoWSGR\controller\windows_controller.py", line 80, in ConnectAndroid if self.is_android_online(5) == False: File "C:\Users\23576\anaconda3\lib\site-packages\AutoWSGR\controller\windows_controller.py", line 101, in is_android_online res = check_output("adb devices -l").decode('ascii').split('\n') File "C:\Users\23576\anaconda3\lib\subprocess.py", line 424, in check_output return run(*popenargs, stdout=PIPE, timeout=timeout, check=True, File "C:\Users\23576\anaconda3\lib\subprocess.py", line 505, in run with Popen(*popenargs, **kwargs) as process: File "C:\Users\23576\anaconda3\lib\subprocess.py", line 951, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "C:\Users\23576\anaconda3\lib\subprocess.py", line 1420, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] 系统找不到指定的文件。

该问题在 github 当前 `main` 分支已经解决。
出现问题的原因是电脑没有安装 adb，或者在系统路径和工作目录下找不到 adb。
感谢反馈。
