### ISSUE TITLE
日常出征船舱满了后解装失败

### ISSUE THREAD

**Issue by yyl893653496** [huan-yp/Auto-WSGR#20]
日常炸鱼，船舱满了，自动清空时报错
![30$UK(8)4O9LMTY)Q`YI2MY](https://github.com/huan-yp/Auto-WSGR/assets/71807633/682626a4-2f6b-4421-bd45-7ad4706c46b0)

**Comment by huan-yp** [comment]
请对比一下你现在用的 config 和我们的 defaul_settings.yaml，版本号大跳动会改配置文件格式，dock_full_destroy 参数的位置发生了改变

**Comment by huan-yp** [comment]
应该修了，如果没问题你就关了吧.
https://github.com/huan-yp/Auto-WSGR/commit/b5a2acce66ac009c3afe2c33a8d417f8dba4232c
