### ISSUE TITLE
fleet_id 读取错误

### ISSUE THREAD

**Issue by liunian321** [huan-yp/Auto-WSGR#25]
当使用默认的fleet_id会启动报错
![image](https://github.com/huan-yp/Auto-WSGR/assets/46080359/74ce87c2-f829-4c58-934e-46b11391a6b3)

当我查看代码
![image](https://github.com/huan-yp/Auto-WSGR/assets/46080359/b3c1087e-6357-4eac-8f6d-7a08dc9c83fc)

发现fleet_id是取的第一层级的？我不是很懂python，觉得default_args['fleet_id']不大可能是递归往下找
当在第一层级加上以后就能正确跑了
![image](https://github.com/huan-yp/Auto-WSGR/assets/46080359/a8174c74-63bd-4af5-968b-b0077bb4fbb6)

**Comment by huan-yp** [comment]
不推荐使用 default_args 里的参数，你可以在 FightFlan 实例化时指定参数或者在 plan 的 .yaml 配置文件中指定舰队，我们提供的参考策略可能不含 fleet_id 参数，需要在 FightPlan 实例化时指定
