### ISSUE TITLE
活动bug（不确定是不是仅活动存在）

### ISSUE THREAD

**Issue by cwlm** [huan-yp/Auto-WSGR#29]
<img width="827" alt="image" src="https://github.com/huan-yp/Auto-WSGR/assets/105329086/3f2a6240-59ef-4493-b5a0-36ab3f98d613">
最终停在这个界面
<img width="661" alt="image" src="https://github.com/huan-yp/Auto-WSGR/assets/105329086/2331818d-dc4b-4b0b-bcbb-6b337146d4ae">

似乎仅在战役支援（每天10次那个）开启时会出现

**Comment by veadex** [comment]
这个啊，你可以把game文件夹下的game_operation.py的第46行改为`timer.Android.click(910, 510, delay=.25, times=2)`
