### ISSUE TITLE
纯萌新提问

### ISSUE THREAD

**Issue by cwlm** [huan-yp/Auto-WSGR#3]
用pip install完之后没有找到setup.py，请问之后应该干什么
python3.7的路径是C:\Users\yww\AppData\Local\Programs\Python

**Comment by huan-yp** [comment]
setup.py 是发布 pypi package 使用的构建代码，请忽略它，直接按照教程使用。

**Comment by huan-yp** [comment]
你使用的是 pypi 安装，只会安装 AutoWSGR 文件夹下的运行代码，examples 是附在 github 上的样例代码，你可以复制下来使用。
建议先测试 print(AutoWSGR.__version__)，如果出现  opencv 相关的报错，请手动降级 opencv-python 到 4.5.5.64 版本。
`pip uninstall opencv-python`
`pip install opencv-python==4.5.5.64`

**Comment by cwlm** [comment]
请问AutoWSGR对examples的路径有要求吗

**Comment by huan-yp** [comment]
AutoWSGR 的使用方式和正常 python package 相同，对路径没有严格的要求。
如果有不明确的地方或者错误，可以在 Issue 里提供对应的细节信息提问。

**Comment by cwlm** [comment]
subprocess.CalledProcessError: Command 'adb devices -l' returned non-zero exit status 1. 报了这个错误，请问是遇到了什么问题

**Comment by huan-yp** [comment]
正常情况不会出现这个问题，怀疑是杀毒软件强行停止了这个进程，如果有杀毒软件就关掉重新运行程序，如果仍然无法运行可以发一下屏幕截图，你提供的信息有点少。
