### ISSUE TITLE
文档的小错误

### ISSUE THREAD

**Issue by cwlm** [huan-yp/Auto-WSGR#38]
[中文文档](../tree/main/documentation/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.md)里面第29行

> [安装 Python](https://zhuanlan.zhihu.com/p/111168324) 注意, Python 版本要求 3.9 <= x <= 3.11, 我们推荐你安装 **[Python3.9.13](https://www.python.org/downloads/release/python-379/).**

> `[Python3.9.13](https://www.python.org/downloads/release/python-379/)`

链接是不是给错了

**Comment by veadex** [comment]
是错了，还是之前的没有改，之后会抽空改一下的

**Comment by Nickydusk** [comment]
已修复，建议发现该类问题提出pr来直接更新
