### ISSUE TITLE
ERROR: Error [WinError 2] 系统找不到指定的文件

### ISSUE THREAD

**Issue by WFAQ233** [huan-yp/Auto-WSGR#41]
Microsoft Windows [版本 10.0.19045.3930]
(c) Microsoft Corporation。保留所有权利。

C:\Users\MR>pip install -U git+https://github.com/huan-yp/Auto-WSGR.git@main
Collecting git+https://github.com/huan-yp/Auto-WSGR.git@main
  Cloning https://github.com/huan-yp/Auto-WSGR.git (to revision main) to c:\users\mr\appdata\local\temp\pip-req-build-u7c492pu
  ERROR: Error [WinError 2] 系统找不到指定的文件。 while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
WARNING: You are using pip version 22.0.4; however, version 23.3.2 is available.
You should consider upgrading via the 'E:\Python-3.9.13\python.exe -m pip install --upgrade pip' command.

C:\Users\MR>

3.9.13python我放到e盘了，pip也没问题。就是不清楚为什么要不到这个东西，群里有简介么dalao？

**Comment by veadex** [comment]
你没有安装git吧，还有建议使用另外一种安装方式

**Comment by Nickydusk** [comment]
请安装git
