### ISSUE TITLE
BUG:决战节点识别错误

### ISSUE THREAD

**Issue by YaoerWu** [huan-yp/Auto-WSGR#68]
![e6a8b923a2c458d707067edbae03d262](https://github.com/user-attachments/assets/28d86183-cf8d-4bcd-b1f5-7b74be31b4d4)
如图所示，节点D打完后将节点E识别成了J，导致脚本进行切图，但是当前图未完成，出错
```
\autowsgr\fight\decisive_battle.py", line 361, in next
    self.timer.ConfirmOperation(timeout=5, must_confirm=1)  # 确认通关
\autowsgr\timer\timer.py", line 568, in ConfirmOperation
    raise ImageNotFoundErr("no confirm image found")
autowsgr.constants.custom_exceptions.ImageNotFoundErr: no confirm image found
```

**Comment by YaoerWu** [comment]
测试结果为两种可能的错误
1. 舰船标识错误识别，识别到左上角的撤退按钮
2. 截图速度太快，导致选择舰队界面未完全消失

**Comment by veadex** [comment]
d16c7909253459f56cb17686cfab8d870cd923d9
