### ISSUE TITLE
求助！

### ISSUE THREAD

**Issue by wssfpyp** [huan-yp/Auto-WSGR#71]
更新1.0后会报如下错
![1](https://github.com/user-attachments/assets/2fec1a73-3c1e-41a8-a8c3-3ce7798b1655)
![2](https://github.com/user-attachments/assets/b14b0e20-9bfc-46db-b004-cab6629ece2b)

**Comment by veadex** [comment]
看一下paddle的版本

**Comment by wssfpyp** [comment]
![image](https://github.com/user-attachments/assets/221296ea-db18-4b4c-98d4-b87905405692)

**Comment by veadex** [comment]
> ![image](https://private-user-images.githubusercontent.com/41791015/372466872-221296ea-db18-4b4c-98d4-b87905405692.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3ODY1NjEsIm5iZiI6MTcyNzc4NjI2MSwicGF0aCI6Ii80MTc5MTAxNS8zNzI0NjY4NzItMjIxMjk2ZWEtZGIxOC00YjRjLTk4ZDQtYjg3OTA1NDA1NjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDEyMzc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyZTAwMjM5Y2ZmYjM4ZmRiMDYxYzlhNzllMTg4NWNjMzczN2Q1ZmU1YmU1ZWM1MzViMDA0N2JhYTRlZmRlYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.akqXcRcbz19SLNXthCHeP9Ikcmzod3dAVqwAseLjRDQ)
能再发一下torch的版本吗

**Comment by wssfpyp** [comment]
![image](https://github.com/user-attachments/assets/ce990d9f-d44f-408e-95d8-b0b67853d24a)

**Comment by wssfpyp** [comment]
> > ![image](https://private-user-images.githubusercontent.com/41791015/372466872-221296ea-db18-4b4c-98d4-b87905405692.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3ODY1NjEsIm5iZiI6MTcyNzc4NjI2MSwicGF0aCI6Ii80MTc5MTAxNS8zNzI0NjY4NzItMjIxMjk2ZWEtZGIxOC00YjRjLTk4ZDQtYjg3OTA1NDA1NjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDEyMzc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyZTAwMjM5Y2ZmYjM4ZmRiMDYxYzlhNzllMTg4NWNjMzczN2Q1ZmU1YmU1ZWM1MzViMDA0N2JhYTRlZmRlYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.akqXcRcbz19SLNXthCHeP9Ikcmzod3dAVqwAseLjRDQ)
> > 能再发一下torch的版本吗

![image](https://github.com/user-attachments/assets/386265e0-9f7d-40d4-897d-bb6010bb2ae6)
