### ISSUE TITLE
名字错误？

### ISSUE THREAD

**Issue by cwlm** [huan-yp/Auto-WSGR#8]
![image](https://user-images.githubusercontent.com/105329086/208830289-0ba40a52-2b39-45fa-8f33-58625a2a449d.png)
![image](https://user-images.githubusercontent.com/105329086/208830350-74da41a5-d09e-4194-8dd7-659920a9b531.png)

**Comment by Nickydusk** [comment]
这个不是名字错误，是目前的屏幕分辨率下OCR识别不了太复杂的汉字，所以要用的话需要把“鲃”等比较精细的汉字改掉

**Comment by huan-yp** [comment]
readme 里写了这个，建议改名成 '肥鱼'，并修改对应的 shipname.yaml

**Comment by cwlm** [comment]
谢谢
